### ISSUE TITLE
Does not handle states based on immutable library.

### ISSUE THREAD

**Issue by leonaves** [alexkuz/redux-devtools-inspector#10]
As mentioned here: https://github.com/chibicode/react-json-tree/pull/32 immutable does not work correctly with this monitor due to a.) a bug in react-json-tree and b.) the fact that the jsondiff view does not consider immutable when generating deltas.

**Comment by ingro** [comment]
Yep I'm experiencing this too.
A working approach may be [this one](https://github.com/whetstone/redux-devtools-diff-monitor/blob/master/src/utils/diff-state.js) from `redux-devtools-diff-monitor` which works quite well with Immutable data!

**Comment by alexkuz** [comment]
I'm bothered that it affects performance significantly, if you have a huge array or object in your state. May be there should be an option in `inspector` that enables full `Immutable` support, I'm not sure.

**Comment by alexkuz** [comment]
Also, I just found out - looks like `Immutable` doesn't support iterators with non-object entries (but maybe it's a valid behaviour, I don't know).

**Comment by ingro** [comment]
Not sure about that, anyway an option could be a good compromise.

**Comment by alexkuz** [comment]
Try this out:

default:
http://alexkuz.github.io/redux-devtools-inspector/

with immutable support in diff:
http://alexkuz.github.io/redux-devtools-inspector/?immutable

in the last example you'll notice performance issues after clicking "push huge array" several times.
