### ISSUE TITLE
Feature request: action cancellation

### ISSUE THREAD

**Issue by billyjanitsch** [alexkuz/redux-devtools-inspector#19]
It would be great if the monitor included [redux-devtools-log-monitor](https://github.com/gaearon/redux-devtools-log-monitor#features)'s action disabling feature:

![](http://i.imgur.com/J4GeW0M.gif)

Clicking some part of an action disables it from the history, causing subsequent states to be recomputed.

It looks like it [wouldn't require much code](https://github.com/gaearon/redux-devtools-log-monitor/blob/master/src/LogMonitor.js) -- I can work on a PR if you're interested in the feature.

**Comment by alexkuz** [comment]
I don't mind adding this feature if you think it's really helpful. For me, it's fun, but pretty useless, actually, so I didn't add it myself yet.

**Comment by billyjanitsch** [comment]
That makes sense. I primarily find the feature useful for async actions: if I dispatch some in sequence and they all resolve quickly, it's nice to get a quick visual confirmation that the intermediate (loading) state is working correctly, and doesn't depend on the resolution order (for this, an action reordering feature would also be great, though likely more work to implement).

Anyway, I understand if you'd prefer not to bloat the project with a feature that you don't use, so I don't mind if you close the issue. I can always work on a fork, and submit a PR if it turns out to be a really minimal amount of added code. Thanks a lot for your work on this project, btw!

**Comment by alexkuz** [comment]
That's a good example. It would be even more useful, probably, to rollback to specific state.
I see it like this: on hover, action row has two icons, instead of time badge: one rolls back to this state (i.e. disables all subsequent actions), another disables this action only.

**Comment by alexkuz** [comment]
`v0.5.0` now supports skipping action, sweeping and committing.
