### ISSUE TITLE
Feature request: Commit

### ISSUE THREAD

**Issue by noseglid** [alexkuz/redux-devtools-inspector#20]
I've gotten used to the Commit feature of the `LogMonitor`, but the ability to diff state in `Inspector` is awesome. Right now I am switching between `LogMonitor` to commit the state and back to `Inspector` to continue work.

I would like to see the commit feature in this monitor too!

**Comment by alexkuz** [comment]
I've never tried it - can you describe how you use it? Is it just like "Clear" button in devtools or is there something more? What about Reset/Revert/Sweep? I don't want to bloat this tool with features, so I need to understand which of them are actually useful.

**Comment by noseglid** [comment]
So essentially it commits everything so you only have the @INIT entry, but with the state you were in. It is useful when I have to perform quite a few state changes before I reach the state where I want to work, and I don't want all those previous state changes bloating my output.

I'm not sure how it works internally, but it seems as committing in `LogMonitor` also puts the `Inspector` in this new state. Is it handled by `DockMonitor`?

**Comment by alexkuz** [comment]
Probably, I'm not sure either :)

**Comment by Mistereo** [comment]
"Commit" by itself is not very useful, but helpful in pair with "Revert", you can for a example, go to some pre-buggy state, "Commit" it, try something, maybe fix a bug and then, instead of repeating all interactions, just press "Revert" to go back to the latest committed state.
"Sweep" is visual only and has no meaning without action cancelation (#19)

**Comment by alexkuz** [comment]
@Mistereo thank you for your input!

**Comment by alexkuz** [comment]
`v0.5.0` now supports skipping action, sweeping and committing.
