### ISSUE TITLE
jss@3.6.1 breaks the UI

### ISSUE THREAD

**Issue by zalmoxisus** [alexkuz/redux-devtools-inspector#24]
With `jss@3.6.0` works well.

With `jss@3.6.1` and `jss@3.6.2`:
<img width="168" alt="screen shot 2016-04-12 at 2 36 46 pm" src="https://cloud.githubusercontent.com/assets/7957859/14458839/bd916326-00bc-11e6-94a9-1d54460276a8.png">

Should we lock to `v3.6.0`?

**Comment by alexkuz** [comment]
Seems like it's fixed in `v3.6.3` - I'll use this version from now.
