### ISSUE TITLE
Support Chrome Extension

### ISSUE THREAD

**Issue by zalmoxisus** [alexkuz/redux-devtools-inspector#27]
Starting from `0.4` the inspector monitor [stores monitor state in devtools](https://github.com/alexkuz/redux-devtools-inspector/commit/52aaf80a869131532aa5106a81e8730d52f2dbe0), which is a great feature, but not for the extension. Imagine that [every 150 ms](https://github.com/alexkuz/redux-devtools-inspector/blob/b2f62e08968ff5c3d9a72c313692138e2b91dee1/src/DevtoolsInspector.js#L103) the extension will dispatch a monitor action to the injected script, will serialize the liftedStore and parse it in the backgrond. It will crash the browser for sure. We can do some optimizations, but anyway it will slow the extension down.

What do you think of having an alternative of the monitor reducers?

**Comment by alexkuz** [comment]
I'm actually fixing it right now :) It shouldn't dispatch every 150 ms, obviously.

**Comment by zalmoxisus** [comment]
Anyway, selecting an action would be slow, the extension should wait the response from the injected script which will process the monitor's reducers and will serialize the liftedStore.

**Comment by alexkuz** [comment]
I see. So there should be a flag that enables storing monitorState in Inspector state, instead of devtools?

**Comment by alexkuz** [comment]
@zalmoxisus btw, it seems like `updateMonitorState` doesn't actually update the state. Is there a reason for it or is it a bug?

**Comment by zalmoxisus** [comment]
Monitors are decoupled from the injected app's devtools. We can apply monitor's reducers like [that](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js#L151) and list monitors actions [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/browser/extension/inject/pageScript.js#L7). I'd like to avoid negotiating monitor's states between the extension and the app, as it would affect the performance and would lead to a lot of issues.

**Comment by alexkuz** [comment]
OK, I've created a PR here https://github.com/zalmoxisus/redux-devtools-extension/pull/103/files, try it out, please.

**Comment by zalmoxisus** [comment]
Thanks a lot! Now it works smoothly [for Remote Redux DevTools as well](https://github.com/zalmoxisus/remotedev-app/commit/01e8455c426524f0298758d6ae98a3f12df5a3e2).
