### ISSUE TITLE
Webpack warns about dynamic requires

### ISSUE THREAD

**Issue by gaearon** [alexkuz/redux-devtools-inspector#3]
<img width="448" alt="screen shot 2016-02-23 at 13 48 48" src="https://cloud.githubusercontent.com/assets/810438/13253744/8972608e-da35-11e5-8da3-8d8d30a70274.png">

This is an upstream issue with `jsondiffpatch`. I’m not sure whether they plan to fix it but I outlined a possible fix [here](https://github.com/benjamine/jsondiffpatch/issues/107#issuecomment-187708784).

Alternative you could use a UMD build instead.

**Comment by benjamine** [comment]
nice, thanks for creating the separate issue @gaearon! I'm planning to do some changes to bundling, not totally happy with current one.

**Comment by gaearon** [comment]
@benjamine Thank you for taking the time to reply and look into this.

**Comment by alexkuz** [comment]
👍
for now I'm just requiring `diffpatcher` directly.
