### ISSUE TITLE
Layout broken with vertical split on chrome

### ISSUE THREAD

**Issue by dkravcovs** [alexkuz/redux-devtools-inspector#33]
Left column is not fully visible in wide mode

![clipboard01](https://cloud.githubusercontent.com/assets/2834813/15957110/9b19b0ac-2ef5-11e6-9ea3-b679ad57cff5.png)

**Comment by jhen0409** [comment]
It's fixed by #32, but not published yet.

**Comment by alexkuz** [comment]
should be fine now
