### ISSUE TITLE
The component is rerendered 2-3 times on every change

### ISSUE THREAD

**Issue by zalmoxisus** [alexkuz/redux-devtools-inspector#41]
Due to the fix of #27, every change invokes the second rerender, because the state is set the second time in `componentWillUpdate` (by calling `this.updateMonitorState`), which is [antipattern](https://facebook.github.io/react/docs/component-specs.html#updating-componentwillupdate):

> You cannot use this.setState() in this method. If you need to update state in response to a prop change, use componentWillReceiveProps instead.

The third rerendering is due to the fact that [we dispatch and action after changing the state](https://github.com/alexkuz/redux-devtools-inspector/blob/master/src/DevtoolsInspector.js#L132),  though it has effect only when `shouldPersistState` is set to `true`. BTW, persisting the monitor state seems to be broken.

The problem is that by rerendering the parent component, `ActionPreview` is also rerendered (and `react-json-tree` and everything inside it).

**Comment by zalmoxisus** [comment]
I'm hacking Redux DevTools extension to handle monitors reducers (on the extension side), so we could remove changes influenced by #27 and not use local state where it's not necessary.

**Comment by alexkuz** [comment]
@zalmoxisus can we close it now?
