### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by macklinu** [alexkuz/redux-devtools-inspector#42]
I am working with the [redux-actions](https://github.com/acdlite/redux-actions) library, which are utilities for creating [FSA-compliant actions](https://github.com/acdlite/flux-standard-action). If an `Error` is supplied to the action creator, an expected action would look like this:

``` js
const increment = createAction('INCREMENT');

const error = new TypeError('not a number');

expect(increment(error)).to.deep.equal({
  type: 'INCREMENT',
  payload: error,
  error: true
});
```

The `redux-devtools-inspector` is having trouble diffing the `Error` payload if it is added to the application's Redux state and throws:

```
Uncaught TypeError: Cannot read property 'length' of undefined
```

At [this line](https://github.com/alexkuz/redux-devtools-inspector/blob/9ce7985f16af9205013bac0b87e0fbe9a62aef55/src/tabs/JSONDiff.jsx#L12) in `src/tabs/JSONDiff.jsx`.

I looked into the [javascript-stringify](https://github.com/blakeembrey/javascript-stringify) function, and it returns `undefined` when supplied an `Error()` - as a result, calling `str.length` in the JSON diff component throws an error. (I am thinking this might be a bug in that library as well? I'm not sure, but can open an issue.)

The quickest way to reproduce this was to update the demo app in this repo to add a reducer that returns an `Error`.

``` diff
diff --git a/demo/src/js/DemoApp.jsx b/demo/src/js/DemoApp.jsx
index 4c4b572..889c75d 100644
--- a/demo/src/js/DemoApp.jsx
+++ b/demo/src/js/DemoApp.jsx
@@ -145,6 +145,9 @@ class DemoApp extends React.Component {
             <Button onClick={this.props.addSymbol} style={styles.button}>
               Add Symbol
             </Button>
+            <Button onClick={this.props.addError} style={styles.button}>
+              Add Error
+            </Button>
           </div>
         </div>
         <div style={styles.links}>
@@ -204,6 +207,7 @@ export default connect(
     }),
     addFunction: () => ({ type: 'ADD_FUNCTION' }),
     addSymbol: () => ({ type: 'ADD_SYMBOL' }),
+    addError: () => ({ type: 'ADD_ERROR' }),
     pushRoute
   }
 )(DemoApp);
diff --git a/demo/src/js/reducers.js b/demo/src/js/reducers.js
index 54ca2d5..974499f 100644
--- a/demo/src/js/reducers.js
+++ b/demo/src/js/reducers.js
@@ -91,5 +91,7 @@ export default {
   addFunction: (state=null, action) => action.type === 'ADD_FUNCTION' ?
     { f: FUNC } : state,
   addSymbol: (state=null, action) => action.type === 'ADD_SYMBOL' ?
-    { s: Symbol('symbol') } : state
+    { s: Symbol('symbol') } : state,
+  addError: (state=null, action) => action.type === 'ADD_ERROR' ?
+    Error() : state
 };
```

I will open a PR with a potential fix for this repo, but perhaps a patch is also needed in javascript-stringify? What do you think?

(Thanks for the awesome tool! ❤️)

**Comment by zalmoxisus** [comment]
@macklinu we're now supporting [`Error` objects in `javascript-stringify`](https://github.com/blakeembrey/javascript-stringify/pull/9) as long as [ES6 Maps and Sets](https://github.com/blakeembrey/javascript-stringify/pull/8).
