### ISSUE TITLE
Bump jss version

### ISSUE THREAD

**Issue by kbrownlees** [alexkuz/redux-devtools-inspector#45]
Trying to install this with yarn fails on node > 6 because jss has version required of node < 6.0.0. The latest version of jss does not have this issue so would be good to upgrade (if possible!).

Thanks for a great tool!

**Comment by GeorgS** [comment]
I've tested it with the latest jss / jss-nested / jss-vendor-prefix versions and it seems to work (https://github.com/alexkuz/redux-devtools-inspector/pull/48).

**Comment by julienvincent** [comment]
+1

**Comment by alexkuz** [comment]
I've merged the PR and updated other dependencies as well. Thank you!

@julienvincent please use reactions instead of "+1"

**Comment by julienvincent** [comment]
@alexkuz Can you make an npm release please.

**Comment by alexkuz** [comment]
Oh, right :)

Done!
