### ISSUE TITLE
Show dispatched action

### ISSUE THREAD

**Issue by quicksnap** [alexkuz/redux-devtools-inspector#9]
This monitor is awesome! Thank you!

Would you accept a PR that shows the current dispatched action at the top? Perhaps only in the "State" view?

**Comment by quicksnap** [comment]
Kind of like how the log monitor displays actions

**Comment by alexkuz** [comment]
Sure! I don't know why I forgot about that, it should be there, obviously :)

**Comment by alexkuz** [comment]
Added in https://github.com/alexkuz/redux-devtools-inspector/pull/14
